name: Build MiniSelfHUD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # نولّد Gradle Wrapper بنسخة 8.10 (أو أي >= 8.8)
      - name: Generate Gradle Wrapper 8.10
        run: |
          gradle wrapper --gradle-version 8.10
          chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build --no-daemon

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: MiniSelfHUD
          path: build/libs/*.jar
